from operations import *

def write_purchase(name, number, user_purchased_laptops, vat_amount, final_total):
    with open(name+str(number)+".txt","w") as file:
        today_date_and_time = datetime.now()
        file.write("\n")
        file.write("\t \t \t \t Bill ")
        file.write("\n")
        file.write("\t \t Kathmandu,Chabahil | Phone No: 98000000")
        file.write("\n")
        file.write("----------------------------------------------------------------------\n")
        file.write("Laptop Details are: \n")
        file.write("----------------------------------------------------------------------\n")
        file.write("Name of the Costumer: "+str(name)+"\n")
        file.write("Contact number: "+str(number)+"\n")
        file.write("Date and time of purchase: "+str(today_date_and_time)+"\n")
        file.write("----------------------------------------------------------------------\n")
        file.write("\n")
        file.write("Purchase Detail are:\n")
        file.write("----------------------------------------------------------------------\n")
        file.write("Item Name \t\t Total Quantity \t\t Unit Price \tTotal\n")
        file.write("----------------------------------------------------------------------\n")
        for i in user_purchased_laptops:
            file.write(str(i[0])+"\t\t\t"+str(i[1])+"\t\t\t"+str(i[2])+"\t\t\t"+"$"+str(i[3])+"\n")
            file.write("----------------------------------------------------------------------\n")
            file.write("\n")
        file.write("Vat amount: "+ str(vat_amount)+"\n")
        file.write("Grand total: "+str(final_total))

def write_sell(name, number, user_purchased_laptops,grand_total):
    with open(name+str(number)+".txt","w") as file:
        today_date_and_time = datetime.now()
        file.write("\n")
        file.write("\t \t \t \t Bill ")
        file.write("\n")
        file.write("\t \t Raniban, Kathmandu | Contact number: 980000000")
        file.write("\n")
        file.write("----------------------------------------------------------------------\n")
        file.write("Laptop Details are: \n")
        file.write("----------------------------------------------------------------------\n")
        file.write("Name of the Costumer: "+str(name)+"\n")
        file.write("Contact number: "+str(number)+"\n")
        file.write("Date and time of purchase: "+str(today_date_and_time)+"\n")
        file.write("----------------------------------------------------------------------\n")
        file.write("\n")
        file.write("Purchase Detail are:\n")
        file.write("----------------------------------------------------------------------\n")
        file.write("Item Name \t\t Total Quantity \t\t Unit Price \tTotal\n")
        file.write("----------------------------------------------------------------------\n")
        for i in user_purchased_laptops:
            file.write(str(i[0])+"\t\t\t"+str(i[1])+"\t\t\t"+str(i[2])+"\t\t\t"+"$"+str(i[3])+"\n")
            file.write("----------------------------------------------------------------------\n")
            file.write("\n")
            file.write("Grand Total: $"+str(grand_total)+"\n")
            file.write("\n")
            file.write("****Note: Shipping cost is added to the grand total****"+"\n")
